# # .github/workflows/deploy.yml

# name: Deploy to Raspberry Pi

# on:
#   workflow_run:
#     workflows: ["Docker Build and Push to Docker Hub"]
#     types:
#       - completed

# jobs:
#   deploy:
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     runs-on: ubuntu-latest

#     steps:
#       - name: Setup SSH
#         uses: webfactory/ssh-agent@v0.8.0
#         with:
#           ssh-private-key: ${{ secrets.RASPI_SSH_KEY }}

#       - name: Deploy via SSH
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.RASPI_USER }}@${{ secrets.RASPI_HOST }} << 'EOF'
#             echo "âœ… Raspi ì ‘ì† ì™„ë£Œ"

#             cd ~/gov-watcher-fe
#             git pull origin main
#             docker compose pull
#             docker compose up -d

#             echo "ðŸš€ FE ìµœì‹ í™” ì™„ë£Œ"
#           EOF
